### ISSUE TITLE
Watch IP for change

### ISSUE THREAD

**Issue by omar-h** [1DC/PynamicDNS#1]
Instead of running on a set interval, you should watch the IP for change and run when it does that.
One way to do this would be to fetch the IP on the set interval, and check if it has changed from the one stored in memory.

If it has, you change it. This way you would be more efficient, and you would be able to have an interval way lower of what you currently have.

**Comment by 1DC** [comment]
Sure, I'll do this.

**Comment by 1DC** [comment]
Completed, closing the issue.
